name: CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install build dependencies
        if: matrix.goos == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libsqlite3-dev

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          ls -la cmd/tt/

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o tt ./cmd/tt/main.go
        env:
          CGO_ENABLED: 1

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tt-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./tt
          if-no-files-found: error

  release:
    name: Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release archive
        run: |
          cd artifacts
          for os in linux darwin windows; do
            for arch in amd64 arm64; do
              if [ "$os" = "windows" ] && [ "$arch" = "arm64" ]; then
                continue
              fi
              binary="tt-$os-$arch/tt"
              if [ "$os" = "windows" ]; then
                binary="${binary}.exe"
              fi
              if [ -f "$binary" ]; then
                zip "tt-$os-$arch.zip" "$binary"
              fi
            done
          done

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/tt-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 