name: Create Release Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to tag (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  check-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is authorized
        if: github.actor != 'stebennett'
        run: |
          echo "Only the repository owner can run this workflow"
          exit 1

  create-tag:
    needs: check-permissions
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create and push tag
        run: |
          git tag -a "v${{ github.event.inputs.version }}" -m "Release v${{ github.event.inputs.version }}"
          git push origin "v${{ github.event.inputs.version }}" 